name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          files: build/libs/*.jar
        continue-on-error: false

      - name: Get GitHub Changelog
        run: |
          changelog=$(gh api repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} --jq '.body')
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "GITHUB_CHANGELOG<<$EOF" >> "$GITHUB_ENV"
          echo "$changelog" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Publish Hangar Release
        run: ./gradlew publishPluginPublicationToHangar
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
        continue-on-error: true

      - name: Publish Modrinth Release
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        continue-on-error: true
